source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

source/webapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from webapp.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserListView, \
    UserDetailView, UserUpdateView


app_name = 'webapp'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('post/create', PostCreateView.as_view(), name='add_post'),
    path('post/update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),
    path('users', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('user/update/<int:pk>', UserUpdateView.as_view(), name='user_update')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='user_info', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон')
    picture = models.ImageField(verbose_name='Фотография')
    friend = models.ManyToManyField('UserInfo', blank=True, related_name='user_friend', verbose_name='Друг')

    def __str__(self):
        return self.user.get_full_name()

class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(max_length=2000, verbose_name='Текст')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    author = models.ForeignKey(UserInfo, on_delete=models.PROTECT, related_name='post_author', verbose_name='Автор')

    def __str__(self):
        return self.title

source/webapp/forms.py
from django import forms
from webapp.models import Post, UserInfo

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['date']

class UserForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        exclude = []

source/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            context = {
                'username': username,
                'password': password,
                'has_error': True
            }
            return render(request, 'login.html', context=context)
        else:
            login(request, user=user)
            return redirect('webapp:post_list')

    return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return redirect('webapp:post_list')

source/webapp/views.py
from django.views.generic import DetailView, CreateView, UpdateView, View, ListView, DeleteView
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from webapp.forms import PostForm, UserForm
from webapp.models import User, Post, UserInfo
from django.contrib.auth.mixins import LoginRequiredMixin

class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'

    def get_queryset(self):
        return Post.objects.order_by('date')

class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'post_update.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.object.pk})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'post_delete.html'

    def get_success_url(self):
        return reverse('webapp:post_list')

class UserListView(ListView):
    model = User
    template_name = 'user_list.html'

class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = UserInfo
    template_name = 'user_update.html'
    form_class = UserForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(pk=self.kwargs.get('pk'))
        return context

    def form_valid(self, form):
        form.instance.userinfo = UserInfo.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:user_detail', kwargs={'pk': self.object.pk})

source/accounts/templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1 class="text-center">Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-text text-danger text-center">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-row form-group">
            <label for="username" class="col-2 form-text">Имя пользователя:</label>
            <input type="text" class="form-control col-10" name="username" id="username">
        </div>
        <div class="form-row form-group">
            <label for="password" class="col-2 form-text">Пароль:</label>
            <input type="password" class="form-control col-10" name="password" id="password">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item navbar-text"><b>Привет, {{ request.user.username }}!</b></li>
                <li class="nav-item active">
                    <a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a>
                </li>
                <li class="nav-item active">
                    <a href="{% url 'webapp:user_detail' request.user.pk %}" class="nav-link">Профиль</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'accounts:login' %}" class="nav-link">Вход</a>
                </li>
            {% endif %}
            <li class="nav-item ml-5">
                <a href="{% url 'webapp:post_list' %}" class="nav-link">Новости</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'webapp:user_list' %}" class="nav-link">Пользователи</a>
            </li>
            {% block menu %}{% endblock %}
        </ul>
    </div>
</nav>
<div class="container mt-4">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/post_create.html
{% extends 'base.html' %}
{% block title %}Добавить пост{% endblock %}
{% block content %}
    <h4>Добавить пост:</h4>
    <form action="{% url 'webapp:add_post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/post_delete.html
{% extends 'base.html' %}
{% block title %}Удалить пост{% endblock %}
{% block content %}
    <h1>Удалить пост</h1>
    <h5>Вы уверены, что хотите удалить пост {{ post.title }}?</h5>
    <form action="{% url 'webapp:post_delete' post.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
{% endblock %}

source/webapp/templates/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост{% endblock %}
{% block content %}
    <div class="m-3">
        <h4>{{ post.title }}</h4>
        <p>Автор: {{ post.author }}</p>
        <p>Дата: {{ post.date }}</p>
    <p>{{ post.text }}</p>
        {% if post.author == self.request.user %}
            <a class="btn btn-dark" href="{% url 'webapp:post_delete' post.pk %}">Удалить пост</a>
            <a class="btn btn-dark" href="{% url 'webapp:post_update' post.pk %}">Изменить пост</a>
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/post_list.html
{% extends 'base.html' %}
{% block title %}Посты{% endblock %}
{% block content %}
    {% if request.user.is_authenticated %}
    <a class="btn btn-dark mb-5 float-right" href="{% url 'webapp:add_post' %}">Добавить пост</a>
    {% endif %}
    {% for post in post_list %}
        <h4><a href="{% url 'webapp:post_detail' post.pk %}">{{ post.title }}</a></h4>
        <p>Автор: {{ post.author }}</p>
        <p>Дата: {{ post.date }}</p>
        <hr>
    {% endfor %}
{% endblock %}

source/webapp/templates/post_update.html
{% extends 'base.html' %}
{% block title %}Изменить пост{% endblock %}
{% block content %}
    <h4>Изменить пост:</h4>
    <form action="{% url 'webapp:post_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Сохранить</button>
    </form>
{% endblock %}

source/webapp/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}
{% block content %}
    <div class="m-3">
    <p><a class="btn btn-dark mb-5 float-right" href="{% url 'webapp:user_update' userinfo.pk %}">Изменить пользователя</a></p>
    <img src="{{ user.user_info.picture.url }}" class="rounded img-thumbnail img-fluid" alt="Фото">
        <p>Логин: {{ user.username }}</p>
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.last_name }}</p>
        <p>E-mail: {{ user.email }}</p>
        <p>Phone: {{ user.user_info.phone }}</p>
        <hr>
    <h5>Друзья:</h5>
    {% for friend in user.user_info.friend.all %}
        <p>{{ friend.user.first_name }} {{ friend.user.last_name }}</p>
    {% endfor %}
        <hr>
    <h5>Посты:</h5>
    {% for post in user.user_info.post_author.all %}
        <p><a href="{% url 'webapp:post_detail' post.pk %}">{{ post.title }}</a></p>
    {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/user_list.html
{% extends 'base.html' %}
{% block title %}Пользователи{% endblock %}
{% block content %}
    {% for user in user_list %}
        <h4><a href="{% url 'webapp:user_detail' user.pk %}">{{ user.first_name }} {{ user.last_name }}</a></h4>
        <hr>
    {% endfor %}
{% endblock %}

source/webapp/templates/user_update.html
{% extends 'base.html' %}
{% block title %}Редактирование пользователя{% endblock %}
{% block content %}
    <h4>Изменить информацию пользователя:</h4>
    <form action="{% url 'webapp:user_update' user.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Сохранить</button>
    </form>
{% endblock %}